service: seek-job-add-checkout-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  lambdaHashingVersion: 20201221

functions:
  createAd:
    handler: lambdas/ad.createAd
    events:
      - http:
          path: ad
          method: POST
          cors: true


resources:
  Resources:
    discountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: discountTable
        AttributeDefinitions:
          - AttributeName: discountId
            AttributeType: S
        KeySchema:
          - AttributeName: discountId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    adTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: adTable
        AttributeDefinitions:
          - AttributeName: adId
            AttributeType: S
        KeySchema:
          - AttributeName: adId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1        