service: seek-job-add-checkout-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello


resources:
  Resources:
    discountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: discountTable
        AttributeDefinitions:
          - AttributeName: discountId
            AttributeType: S
          - AttributeName: discountType
            AttributeType: S
          - AttributeName: adType
            AttributeType: S
        KeySchema:
          - AttributeName: discountId
            KeyType: HASH